import Header from '@/components/Header';
import '../../styles/globals.css';
import Banner from '@/components/Banner';
import Head from 'next/head';

export const metadata = {
  title: 'Alex the Adventurer Blog',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" type="image/png" href="/icon.png" />
      </Head>
      <body className='max-w-7xl mx-auto'>
      <Header />
      <Banner />
        {children}
      </body>
    </html>
  );
};
